### ISSUE TITLE
Docs: Add examples of connecting to BI tools

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb.github.io#119]
## Description

I think a really solid use case is to simplify the BI workflow. It'd be nice to have a few examples of how to connect to tableau, metabase, power bi, etc. 

I know most of these can connect through postgres, but I think it'd still be a nice e2e example showcasing glaredb.

**Comment by greyscaled** [comment]
Rearch started this, and will continue it. We should open issues for specific ones
