### ISSUE TITLE
Docs: Add docs for creating external tables with local files

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb.github.io#175]
## Description

Related: https://github.com/GlareDB/glaredb/issues/1858

I did a quick search and didn't find anything on using local files in our docs site. Also we're missing 'local' in https://docs.glaredb.com/glaredb/sql-commands/create-external-table/

**Comment by greyscaled** [comment]
can get this out soon

**Comment by greyscaled** [comment]
rearch
