### ISSUE TITLE
Docs: Move "supported data sources" to top-level

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb.github.io#211]
## Description

It's currently nested, making it hard to find.

<img width="288" alt="Screenshot 2024-01-04 at 11 40 59 AM" src="https://github.com/GlareDB/glaredb.github.io/assets/4040560/00421c19-f918-48e7-a428-0ace0566c5ea">

**Comment by greyscaled** [comment]
This will be addressed in #224
