### ISSUE TITLE
Docs:  COPY ... TO ...

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb.github.io#74]
## Description

```
COPY table TO 'gs://my_bucket/table/ (FORMAT PARQUET);
```

```
COPY (select ...) TO 's3://my_bucket/output/ (FORMAT JSON);
```

Exact options still being hammered out.

**Comment by greyscaled** [comment]
Command is still in an early state, in a future release (after `v0.2.0`) there will be remote persistance support and likely changes to the SQL syntax.

In the future we might want to mark individual SQL commands with any or all of:

- version introduced
- version last changed
- history of change
- whether we consider the syntax/command stable or experimental
